### ISSUE TITLE
MinGW actions don't use MinGW with CMake

### ISSUE THREAD

**Issue by cmazakas** [alandefreitas/cpp-actions#4]
In order to use MinGW with CMake, specifying the compilers isn't enough as CMake will simply ignore them and then default back to cl.exe

The cpp-matrix action should include something such as:
```js
} else if (compilerName === 'mingw') {
    entry['cxx'] = `g++`
    entry['cc'] = `gcc`
    entry['generator'] = 'MinGW Makefiles'
}
```

In addition to this, CMake doesn't seem to then like the `C:\mingw64\bin\g++` paths and will complain about invalid escapes so I found I needed to add this:
```js
compiler_path = compiler_path.replaceAll('\\','/')
```
in setup-cpp/index.js

**Comment by cmazakas** [comment]
https://github.com/alandefreitas/cpp-actions/actions/runs/7224235865/job/19685067880#step:9:299

Yeah, @alandefreitas this is exactly what I ran into! Did you eventually find a fix for this?

**Comment by alandefreitas** [comment]
Just fixed this one. There were a number of other things that needed to change but it should be good now.
